#!/bin/bash

# build a whole Android application
# wrapper of android/ndk-build/ant/adb tools

if [[ $# -ne 0 ]] && [[ $# -ne 1 ]] && [[ $# -ne 2 ]]; then
    echo "Usage: ./make <id> <release>"
    echo "example: ./make android-23 1"
    exit -1
fi

# prepare args
targetId=android-23
if [[ $# -eq 1 ]]; then
    targetId=${1}
fi
ver=debug
if [[ $# -eq 2 ]]; then
    if [[ ${2} -eq 1 ]]; then
        ver=release
    fi
fi
apkName=ApiDemo

# build apk
echo "1. generate build configuration files ..."
android update project -n ${apkName} -p . -t ${targetId}
if [[ $? -ne 0 ]]; then
    echo "gen java failed!"
    exit -1
fi
echo "2. build NDK libraries ..."
if [[ -d ./jni ]]; then
    ndk-build clean
    ndk-build
    if [[ $? -ne 0 ]]; then
        echo "ndk build failed!"
        exit -1
    fi
fi
echo "3. build APK ..."
ant clean
ant ${ver}

# install
echo "4. install APK ..."
echo "----------"
adb devices | grep -w "device" 1> /dev/null
if [[ $? -ne 0 ]]; then
    echo "Error: device NOT found!"
    exit -1
fi
if [[ "${ver}" == "debug" ]]; then
    adb install -r bin/${apkName}-debug.apk
else
    echo ">>> NOTE: type the passowrd as requested: 122333\n"
    jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore my.key bin/${apkName}-${ver}-unsigned.apk test
    zipalign -v 4 bin/${apkName}-${ver}-unsigned.apk ${apkName}-signed.apk
    adb install -r ${apkName}-signed.apk
fi
